# Разработчик плагина: Soldi_n .jra
# Конфигурация Soldinoponiton
# Все зелья можно стакать до указанного лимита. Объединение II->III в наковальне стоит указанное количество уровней.
max-stack: 64
combine-third-level: true
combine-cost: 5
