name: Build Soldinoponiton

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven
      - name: Build with Maven
        run: mvn -B -DskipTests package
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Soldinoponiton-jar
          path: target/*.jar
